# Data Analysis
## Data Analysis
### Data Analysis
#### Data Analysis 
##### Data Analysis
###### Data Analysis


###### python
##### python
#### python
### python
## python
# python

### python
- List
   - []
- Tuple
   - ()
- Sets
    - {}
- Strings
   - " "or' '
- Dict
   - {}

- *welcome to apssdc*
- **welcome to apssdc**
- ***welcome to apssdc***
 

##  python libraries
- Numpy

In [4]:
# create 1D array
import numpy
a = numpy.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
# create 2D array
import numpy as np
a1 = np.array([[1,2,3,4],[5,6,7,8]])
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
# create 3D array
import numpy as np
a2 = np.array([[1,2,3,4],[5,6,7,8],[1,4,3,5]])
print(a2)

[[1 2 3 4]
 [5 6 7 8]
 [1 4 3 5]]


In [13]:
a2.ndim


2

In [16]:
a2.size

12

In [21]:
a2.shape

(3, 4)

In [26]:
a2[0,1]

2

In [27]:
np.random.randn(1)

array([-0.82596311])

In [28]:
np.random.randn()

0.001919238592548089

In [29]:
np.random.randn(1,10)

array([[-1.02944743,  1.7701774 , -0.50346528,  0.1287555 , -0.8894832 ,
         1.20915537, -0.40324666, -1.40207976,  0.96238252, -0.38456175]])

In [39]:
a=np.random.randint(1,20,15)
print(a)

[ 6  4 15 15 11 19 12 12 16  7 11 14  2  5 16]
